alphagov/di-auth-oidc-provider

ci/pipeline.yaml

- Create a concourse job to print hello world when there has been changes to the repo
- Create a concourse job to update the pipeline when there has been a change to the pipeline.yaml file
- Configure the pipeline to listen to the bau-pipeline-setup branch so we can get quicker feedback when configuring it to deploy the app to PaaS

BAU - Create pipeline skeleton for deploying this application

---

src/main/java/uk/gov/di/resources/AuthorisationResource.java

Add logged-in check in authorize resource.
Create skeleton paths for logged-in and not logged-in cases.

BAU: add logged-in check in authorize resource

---

build.gradle
src/test/java/uk/gov/di/AuthorisationResourceTest.java
src/test/resources/oidc-provider.yml

- Test the authorize endpoint can successfully handle an authorization request.

0XSvsICt - Write integration test for /authorize endpoint

---

.secrets.baseline
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/views/LoginView.java
src/main/java/uk/gov/di/views/PasswordView.java
src/main/java/uk/gov/di/views/SuccessfulLoginView.java
src/main/resources/uk/gov/di/views/login.mustache
src/main/resources/uk/gov/di/views/password.mustache
src/main/resources/uk/gov/di/views/successful-login.mustache
src/test/java/uk/gov/di/AuthorisationResourceTest.java

* Drop a cookie when user succesfully completes login
* Pass authentication request through the login process

OXSvsICt: Add login state to flow

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/UserInfoResource.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java

Add simple userinfo endpoint that returns a static dataset
We are creating a standard set of endpoints for the provider.

OXSvsICt: Add a simple userinfo endpoint

---

src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/services/UserValidationService.java
src/main/java/uk/gov/di/views/LoginView.java
src/main/java/uk/gov/di/views/PasswordView.java
src/main/resources/uk/gov/di/views/login.mustache
src/main/resources/uk/gov/di/views/password.mustache
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/services/UserValidationServiceTest.java

* Validates against a hard-coded username and password for the time being
* Redirects back to the login page if validation fails

OXSvsICt: Validate username and password

---

src/main/resources/uk/gov/di/views/layout.mustache
src/main/resources/uk/gov/di/views/login.mustache
src/main/resources/uk/gov/di/views/password.mustache
src/main/resources/uk/gov/di/views/successful-login.mustache

Use Mustache's templating feature to reduce the amount of repeated boilerplate in the login UI views.
Repeating the same boilerplate in each view template soon become cumbersome and unmanageable.

OXSvsICt: Use a common layout for all page templates

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java

We had previous written some resource tests as integration tests, we've now found a way of doing this as unit tests, so are re-factoring.
It's better!

BAU: Refactor resource tests 

---

src/main/java/uk/gov/di/resources/UserInfoResource.java
src/main/java/uk/gov/di/services/UserValidationService.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/services/UserValidationServiceTest.java

- Make sure the login details required match up to the details returned at the /userinfo endpoint

OXSvsICt - Configure the users login details

---

sql/V1__create_client_configuration_table.sql
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/services/ClientService.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java

Create a ClientService with a list of all valid clients for the authentication service.
Use this in the endpoints to validate whether the request has come from a valid client or not.

ikXzZaOa: Add client config store and validate client id

---

src/main/java/uk/gov/di/OidcProviderApplication.java

Add callbacks that will work both in PaaS and locally.

ikXzZaOa: Add valid callback URLs for the client.

---

src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/services/ClientService.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java

Add an additional form parameter `client_secret` on the token end point and validate this value alongside `client_id`

ikXzZaOa: Validate client secret as well as client ID

---

build.gradle
ci/pipeline.yaml
pre-commit.sh
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/configuration/OidcProviderConfiguration.java
src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/services/ClientService.java
src/main/java/uk/gov/di/services/TokenService.java
src/main/java/uk/gov/di/services/UserValidationService.java
src/main/java/uk/gov/di/views/LoginView.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java
src/test/java/uk/gov/di/services/UserValidationServiceTest.java

Add spotless formatter to gradle build script.
Exclude spotlessApply from build pipeline.
Add reformatted code.
Added pre-commit script so people don't forget to run the tests.
Single standard for formatting applied and enforced by the pipeline.

BAU: add spotless

---

src/main/java/uk/gov/di/OidcProviderApplication.java

Add additional scopes to the OP.
stub-rp requires support of additional scopes.

BAU: fix scopes for stub-rp

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/exceptions/InvalidClientException.java
src/main/java/uk/gov/di/helpers/AuthenticationResponseHelper.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/services/ClientService.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/services/ClientServiceTest.java

* Send an error response back to client with relevant error code in result of an invalid authentication request
* Refactor response generation and client service

ikXzZaOa: Generate error response for invalid requests

---

build.gradle
oidc-provider.yml
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/configuration/OidcProviderConfiguration.java
src/main/java/uk/gov/di/services/ClientConfigService.java
src/main/java/uk/gov/di/services/PostgresService.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java

- Use the vcap env variable set in the app to pull out the credentials to connect to the database and set them in the JDBI datasource factory.

EO8fyrJq - Connect to the postgres database service

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/services/PostgresService.java

Set db connection uri by reading from VCAP_SERVICES
Url in DATABASE_URL is not the one it's looking for.

BAU: set db connection uri by reading from VCAP_SERVICES

---

src/main/java/uk/gov/di/services/PostgresService.java

Tweak jdbi uri used to connect from the database.
Fix hostnotfound exception

BAU: tweak jdbc uri

---

build.gradle
ci/pipeline.yaml
gradle/wrapper/gradle-wrapper.properties
manifest.yml
src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/services/ClientService.java

- BAU: Upgrade to Gradle 7
- BAU: Upgrade pipeline image to Gradle 7/Java 16
- BAU: Remove Spotless, it blocks the upgrade to 16
- BAU: Bump Java version in PaaS manifest
- BAU: Make Client a record

BAU: Upgrade to Java 16

---

manifest.yml
oidc-provider.yml
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/services/PostgresService.java

Construct JDBC connection string by parsing `VCAP_SERVICES` environment variable.
Open connection to backing database.
Add service to `manifest.yml`
We are going to be storing client configuration in the database, so we need a connection to it.

1WQSBhCg - Connect to Postgres

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/services/PostgresService.java

- Make Postgres service method static
- Because we are only ever calling one method once so we don't need to bother creating an instance of the class

BAU - Make Postgres service method static

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/entity/VcapServices.java
src/main/java/uk/gov/di/helpers/AuthenticationResponseHelper.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/LogoutResource.java
src/main/java/uk/gov/di/resources/RegistrationResource.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/resources/UserInfoResource.java
src/main/java/uk/gov/di/services/AuthenticationService.java
src/main/java/uk/gov/di/services/ClientConfigService.java
src/main/java/uk/gov/di/services/ClientService.java
src/main/java/uk/gov/di/services/CognitoService.java
src/main/java/uk/gov/di/services/PostgresService.java
src/main/java/uk/gov/di/services/UserService.java
src/main/java/uk/gov/di/views/ConfirmRegistration.java
src/main/java/uk/gov/di/views/SetPasswordView.java
src/main/java/uk/gov/di/views/SuccessfulRegistration.java
src/test/java/uk/gov/di/entity/VcapServicesTest.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/RegistrationResourceTest.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java
src/test/java/uk/gov/di/services/AuthorizationCodeServiceTest.java
src/test/java/uk/gov/di/services/ClientServiceTest.java
src/test/java/uk/gov/di/services/TokenServiceTest.java
src/test/java/uk/gov/di/services/UserServiceTest.java

Spotless applied.
It still doesn't support so this is a one-off using:
https://github.com/alphagov/di-auth-oidc-provider/commit/72933900edf9071d326430b3e36baafefadbe947
and switching to Java 15 to do spotlessApply
Keep it clean.

BAU: spotless applied

---

.gitignore

Update gitignore for users of vscode.
Loading the project in vscode generates some additional config files which should be ignored by git.

BAU: update gitignore for users of vscode

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/WellKnownResource.java

Stub out the contents of the openid discovery endpoint

chHlFRUD: Stub out /.well-known/openid-configuration

---

src/main/java/uk/gov/di/resources/WellKnownResource.java

chHlFRUD: OIDC configuration was invalid JSON

---

src/main/java/uk/gov/di/resources/UserInfoResource.java

Add additional logging for exceptions in userInfo
See what happens if the accessToken cannot be parsed.

BAU: add additional logging for exceptions in userInfo

---

sql/R__insert_client_configuration.sql
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/resources/WellKnownResource.java
src/main/java/uk/gov/di/services/TokenService.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/services/TokenServiceTest.java

- Add an endpoint to publish the JWKS
- Update wellknown config to use correct hostnames
- Update wellknown config to use correct path to JWKS
- Make sure subject from `userinfo` matches that in the ID token.
To make compliant with "strict" client implementations.

BAU: JWKS endpoint and consistent subjects

---

src/main/java/uk/gov/di/resources/WellKnownResource.java

Clean up endpoint with only things that are supported by the OIDC provider and also use nimbus lib.

Update wellknown endpoint

---

sql/R__insert_client_configuration.sql

Does precisely what it says on the tin

BAU: Add default Spring Security callback url to callback safelist

---

sql/R__insert_client_configuration.sql

BAU - Add closing quotes

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
src/main/java/uk/gov/di/resources/ClientRegistrationResource.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/WellKnownResource.java
src/main/java/uk/gov/di/services/ValidationService.java
src/main/java/uk/gov/di/validation/EmailValidation.java
src/main/java/uk/gov/di/views/LoginView.java
src/main/resources/uk/gov/di/views/login.mustache
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/services/TokenServiceTest.java
src/test/java/uk/gov/di/services/ValidationServiceTest.java

Implement correct validation for email addresses.
Use backend rather than frontend validation so that we can control the display of error messages and thus provide a more consistent user experience.

LTG-22: Implement correct validation for email addresses

---

acceptance-tests/build.gradle
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/RunCucumberTest.java
acceptance-tests/src/test/java/uk/gov/di/test/acceptance/StepDefinitions.java
acceptance-tests/src/test/resources/cucumber.properties
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/Login Journey.feature
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/is_it_friday_yet.feature
settings.gradle

Acceptance tests groundwork with Cucumber.
Add an acceptance-tests module based on Cucumber.
Create a first happy-path scenario to login a user from the sample RP service, through the OP.
Enable automated acceptance testing of the applications.

LTG-101: acceptance tests groundwork with cucumber

---

ci/pipeline.yaml

Run acceptance tests in the pipeline.
Step towards running the acceptance tests before deployment.

LTG-101: run acceptance tests in the pipeline

---

ci/pipeline.yaml

Delete Selenium after acceptance tests.
Rather than leave it there.

LTG-101: delete Selenium after acceptance tests

---

README.md

- Update readme
- We are stopping development in this repo and carrying it on in https://github.com/alphagov/di-authentication-api and https://github.com/alphagov/di-authentication-frontend

LTG-193 - Add note to readme about the future of di-authentication
