alphagov/di-auth-oidc-provider

ci/pipeline.yaml
manifest.yml
src/main/java/uk/gov/di/HelloWorld.java

- Add a manifest to the application so it can run on PaaS. This has been tested to work by manually running cf push. This can be tested by visiting `https://di-auth-oidc-provider.london.cloudapps.digital/hello`
- Start modifying the pipeline to do this automatically for us.
- Configure the pipeline to listen to changes from the `main` branch.

BAU - Configure the app to run on PaaS

---

ci/pipeline.yaml

Add further PaaS deployment tasks to the pipeline.
Enables deploying the app as long as the credentials are set correctly in SSM.

BAU: deploy app to PaaS from the pipeline

---

ci/pipeline.yaml

Be explicit about which Gradle image to use, the implied `gradle:latest` is JDK8, so out of sync with local and deployment environments which are all fixed at 15.
Code failed to build in pipeline once we used a Java 14+ feature.

BAU: Fix Java and Gradle versions in pipeline

---

ci/pipeline.yaml

In the previous commit we incorrectly specified the image tag as part of the repository field, this should infact be specified as a separate field in the pipeline definition.
The pipeline is still failing.

BAU: Use correct syntax for specifying image_resource tag in pipeline.

---

build.gradle
oidc-provider.yml
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/configuration/OidcProviderConfiguration.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/services/TokenService.java
src/test/java/uk/gov/di/TokenResourceTest.java
src/test/resources/oidc-provider.yml

- This PR adds a `/token` endpoint to the di-auth-oidc-provider. This endpoint returns a OIDCTokenResponse.
- The token endpoint expects a `client_id` and authorization code
- The bearer access token is created using the nimbus library
- We can create the ID token claim set using the nimbus library but we need to generate the header and signature of the ID token manually. To do this we generate a new signing key on the fly which will then sign the token. 
- Add an integration test to ensure the response is successful.
**TODO** 
- Validate the token request

Oxsvsict - Add token endpoint

---

src/test/java/uk/gov/di/resources/TokenResourceTest.java

Fix TokenResource unit test failures
client_secret form parameter was missing.

BAU: fix TokenResource unit test failures

---

src/main/java/uk/gov/di/services/PostgresService.java

- The VCAP services doesn't provide the URL as we require for the DataSourceFactory configuration so we need to construct it ourselves.

EO8fyrJq - Configure URL which we use to connect to the PaaS

---

src/main/java/uk/gov/di/OidcProviderApplication.java

Enable env var substitution in Dropwizard config.
We are using environment variables for JDBI config.

BAU: enable env var substitution in dropwizard config

---

build.gradle

Add gradle task to push to PaaS.
So you don't forget to compile if pushing manually

BAU: add gradle task to push to paas

---

build.gradle
sql/R__insert_client_configuration.sql
src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/services/ClientConfigService.java

Add a SQL script to pre-populate client configuration in the database
Add code to ClientConfigService to read data from database.
We want to read client configuration from a data store rather than have it hard-coded.
#41

1WQSBhCg: Get client configuration from database

---

build.gradle
docker-compose.yml
oidc-provider.yml
startup.sh

* Instance is provided by docker-compose
* Missing dependency (org.postgresql) was added for driver
* Default configuration user/pass/name added in manifest

ikXzZaOa: Enable provider to run against a local Postgres instance

---

docker-compose.yml
startup.sh

Add a wait for the Postgres healthcheck to pass before continuing.
Add Flyway in to docker-compose and run `flyway migrate` in `startup.sh` to ensure migrations are run.
This makes it nice and easy to run the IDP locally without needing to manually apply SQL scripts.

BAU: Wait for Postgres and use Flyway for migrations

---

build.gradle
src/main/java/uk/gov/di/entity/VcapServices.java
src/main/java/uk/gov/di/services/PostgresService.java
src/test/java/uk/gov/di/entity/VcapServicesTest.java

Reads the postgres configuration out of `VCAP_SERVICES` using Jackson rather than hand-manipulating the tree.
This is more testable.

ikXzZaOa: Deserialise VCAP_SERVICES with Jackson

---

src/main/java/uk/gov/di/entity/VcapServices.java
src/test/java/uk/gov/di/entity/VcapServicesTest.java

This (in theory) fixes the build.
The VCAP_SERVICES key for the database is `postgres` not `postgresql`

BAU: Fix VCAP provider

---

src/main/java/uk/gov/di/entity/VcapServices.java
src/test/java/uk/gov/di/entity/VcapServicesTest.java

MessageFormat.format splits thousands with commas, which is invalid for our port

ikXzZaOa: Read port as a String rather than an int

---

src/main/java/uk/gov/di/OidcProviderApplication.java

Set the `LOCATION_HEADER_RELATIVE_URI_RESOLUTION_DISABLED` to true to stop the webserver sending fully qualified redirects including the wrong scheme which cause issues in PaaS when running behind an HTTPS proxy.
When running in PaaS the redirection to the user registration journey is currently causing security warnings as it first redirects to `http://....` rather than `https://...`

4QAoG2dk: Fix HTTP/HTTPS redirection issues.

---

.gitignore
build.gradle
startup.sh

Instead of using a nasty bash loop use the Avast Gradle plugin for docker-compose to start the database and run migration scripts.
Using the Gradle plugin gives a cleaner startup script and makes it easier to start the app within a Gradle aware IDE.

BAU: Use docker-compose Gradle plugin to simplify the startup script

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/RegistrationResource.java
src/main/java/uk/gov/di/services/UserService.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/RegistrationResourceTest.java
src/test/java/uk/gov/di/services/UserServiceTest.java

Add a simple, in memory, user back end that stores users credentials as they complete registration journeys.
To persist user data between journeys.

aYkXL8o0: Add user backend in memory

---

src/main/java/uk/gov/di/services/UserService.java

Create a map of `UserInfo` objects in the User Service
We want to store user information collected during registration and have the `userinfo` endpoint return it rather than the current static values.

aYkXL8o0: Add map of user info

---

src/main/java/uk/gov/di/services/TokenService.java
src/test/java/uk/gov/di/services/TokenServiceTest.java

Store access tokens we issue and associate them with the correct user.
This is another step along the way of ensuring that the `userinfo` endpoint returns the correct detail.
#52

aYkXL8o0: TokenService now persists access tokens

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/helpers/AuthenticationResponseHelper.java
src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/services/AuthorizationCodeService.java
src/main/java/uk/gov/di/services/ClientService.java
src/test/java/uk/gov/di/resources/AuthorisationResourceTest.java
src/test/java/uk/gov/di/services/AuthorizationCodeServiceTest.java
src/test/java/uk/gov/di/services/ClientServiceTest.java

Implement a new service to issue and track authorisation codes and track them against the user.
Change the validateAuthenticationRequest method to check for, and return, errors in the authentication request.
Change the ClientService to use the AuthorisationCodeService to issue auth codes.
This is another step along the way of ensuring that the `userinfo` endpoint returns the correct detail.
#53 
#52

aYkXL8o0: Add authorisation code service

---

src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/resources/RegistrationResource.java
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/RegistrationResourceTest.java

Temporarily store email address in cookie after successful login or registration (quick and dirty approach for the spike).
So that the correct user will be stored against the authorisation code when it is issued.
#52
#53
#54

aYkXL8o0: Store email address in cookie

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/TokenResource.java
src/main/java/uk/gov/di/services/AuthorizationCodeService.java
src/test/java/uk/gov/di/resources/TokenResourceTest.java
src/test/java/uk/gov/di/services/AuthorizationCodeServiceTest.java

Only permit tokens to be issued when requested with authentication codes that we have already issued.
So people can't just claim tokens however they want.

aYkXL8o0: Validate issuing of tokens against authorization codes

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/UserInfoResource.java
src/main/java/uk/gov/di/services/UserService.java
src/test/java/uk/gov/di/resources/UserInfoResourceTest.java
src/test/java/uk/gov/di/services/UserServiceTest.java

Only allow UserInfo requests that have a recognised access token
Don't want people querying user info if they don't have permission for it.

aYkXL8o0: Validate requests for UserInfo

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/LogoutResource.java

Add logout endpoint that will expire the cookie so that journeys can be re-run.
We would like to be able to logout from the services while demo-ing journeys. We will add a link to the endpoint on the stub RP.

XytEISqB: Add a logout endpoint

---

startup.sh

Add startup.sh switch to enable Cognito.
Only want to authenticate to AWS if testing against Cognito.
Stop the AWS login dialog from appearing when it's not needed.

BAU: add startup.sh switch to enable cognito

---

build.gradle

Enable JVM debugger when running application.
Useful when debugging applications.

BAU: Enable JVM debugger when running application.

---

src/main/resources/uk/gov/di/views/confirm-registration.mustache
src/main/resources/uk/gov/di/views/login.mustache
src/main/resources/uk/gov/di/views/set-password.mustache
src/main/resources/uk/gov/di/views/successful-registration.mustache

Use gov-uk fonts where missing.
Paragraph fonts not using standard gov-uk fonts in some places as per the design system.

BAU: use gov-uk fonts where missing

---

src/main/java/uk/gov/di/resources/AuthorisationResource.java
src/main/java/uk/gov/di/services/ClientService.java

- Refactor use of isPresent
- We can avoid using isPresent by attempting to map it to what we require and if that doesn't exist then return the alternative response. This follows what is recommended in the GDS way java style guide https://gds-way.cloudapps.digital/manuals/programming-languages/java.html#optionals

BAU - Refactor use of isPresent

---

src/main/java/uk/gov/di/resources/RegistrationResource.java
src/main/java/uk/gov/di/views/ConfirmRegistrationView.java
src/main/java/uk/gov/di/views/SuccessfulRegistrationView.java

Use consistent naming for views.
All should have a 'View' suffix.

BAU: use consistent naming for views

---

src/main/java/uk/gov/di/entity/Client.java
src/main/java/uk/gov/di/entity/ClientRegistrationRequest.java
src/main/java/uk/gov/di/resources/ClientRegistrationResource.java
src/test/java/uk/gov/di/resources/ClientRegistrationResourceTest.java

Add an endpoint at `/register/connect` that accepts a `ClientRegistrationRequest` object.
Do not validate any access tokens.
Adds an alternative method for dynamic client registration.
#68

LaFbWXIf: Add RESTful endpoint for client registration.

---

.dockerignore
Dockerfile

- Created dockerfile to build and run a di-auth-oidc-provider image.
- Added a .dockerignore file to ignore some files.
Adding a dockerfile to allow easy cross collaboration between teams by allowing other teams to build and run the `di-auth-oidc-provider` project locally.

dockerfile: Adding a dockerfile for easy building and running

---

src/main/java/uk/gov/di/resources/WellKnownResource.java

- The python lib expects there to be a grant_types_supported in the well known endpoint, even though it is optional in the spec
- The python lib expects that to exist

BAU - Add grant_types_supported to the well known endpoint

---

sql/R__insert_client_configuration.sql

- Add redirect URI for Python Client
- So the Python client can use the Dummy service credentials

BAU - Add redirect URI for Python Client

---

README.md
db-migrate.sh
sql/V1__create_client_configuration_table.sql
sql/V3__create_whitelist_table.sql

Add script to aid applying Postgres schema updates to PaaS services
Update README.md to explain usage.
We currently don't have a pipeline to apply these, so this makes it easier to run from developer workstations.

BAU: Add script to aid applying Postgres schema updates to PaaS services

---

ci/pipeline.yaml
ci/terraform/site.tf
ci/terraform/variables.tf

- We have now created a "concourse-deployer" role for the pipeline that can be assumed by the Concourse workers.
- Use this new role by configuring Terraform to assume it rather than injecting tokens.
- This can be overridden when running locally by using dev role, e.g. `terraform apply -var 'deployer_role=chris.clayson-admin`
Injecting long-lived access tokens, is not the best practice, after merging we will destroy those tokens.

LTG-109: Use assume role in Terraform

---

ci/pipeline.yaml
ci/terraform/site.tf
ci/terraform/variables.tf

We need to inject the role ARN into Terraform in two places, once for the state backend and once for the AWS provider.
The ARN has been configured in parameter store in the key /cd/concourse/pipelines/verify/di-auth-oidc-provider/deployer-role-arn.
Leaving this parameter blank will allow it be run locally having first done a `eval $(gds aws digital-identity-dev -e)`
The pipeline is currently failing because it can't read the state bucket.
This change also makes it easier to run locally without additional parameters.
#Related PRs
#87

BAU: Inject assume role ARN into Terraform in pipeline

---

src/main/java/uk/gov/di/resources/LoginResource.java
src/main/java/uk/gov/di/services/CognitoService.java
src/main/resources/uk/gov/di/views/layout.mustache

- The copyright symbol was showing a 'Â' special character before it. 
- Access the Stub RP https://di-auth-stub-relying-party.london.cloudapps.digital/ and click `GOV.UK Account`. At the bottom you can then see the Crown copyright symbol with the special char before. 
- Remove some whitespace 
- We can mitigate this by explicitly setting the encoding to UTF-8 in the layout.mustache

LTG-21 - Set the charset to utf-8 in the meta tag

---

ci/pipeline.yaml

Exclude acceptance-tests:test task when running build.
Cucumber tests cannot currently be run in the pipeline so the deploy task is failing.

LTG-101: exclude acceptance-tests:test task when running build

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/StepDefinitions.java
manifest.yml

Allow running of acceptance against a remote Selenium hub
Stand-up Selenium in PaaS (TODO: secure the host with a route service)
To allow us to run acceptance tests in the pipeline.

LTG-101: Acceptance tests in pipeline

---

src/main/java/uk/gov/di/OidcProviderApplication.java
src/main/java/uk/gov/di/resources/RegistrationResource.java
src/main/java/uk/gov/di/services/ValidationService.java
src/main/java/uk/gov/di/validation/PasswordValidation.java
src/main/java/uk/gov/di/views/SetPasswordView.java
src/main/resources/uk/gov/di/views/set-password.mustache
src/test/java/uk/gov/di/resources/LoginResourceTest.java
src/test/java/uk/gov/di/resources/RegistrationResourceTest.java
src/test/java/uk/gov/di/services/ValidationServiceTest.java

- Validate that the password is not empty.
- Validate that the retyped password is not empty.
- Validate that the password is at least 8 characters long.
- Validate that the password contains a number.
- Validate that the 2 password fields match
- Depending on where the validation fails, add the correct error message in the format outlined in the GOV.UK design system. The error messages have been documented here - https://docs.google.com/document/d/190S1eOHxrDKJdZDpYg2qJx5ObRHycU4oCVECOm5JoTo/edit
- Switch off HTML5 validation on the form as advised in the design system docs https://design-system.service.gov.uk/patterns/validation/
- So we can be confident that the user has selected a secure password

LTF-134 - Validate passwords

---

Dockerfile
docker-compose.yml
pre-commit.sh
sql/R__insert_client_configuration.sql

- Add Selenium service to docker compose
- Add IDP and RP to docker compose with appropirate config
- Add additional callback URL to IDP client table
- Run acceptance tests from pre-commit.sh
Acceptance tests can either be run by manually starting services and then
running `./gradlew cucumber` (which will run everything locally using Firefox web driver),
or by running `./pre-commit.sh`, this will start the services dockerized alongside selenium and
use the RemoteWebDriver to control Selenium.
Having the docker-compose option means developers do not need to have Firefox and Gecko web-driver available locally, which has historically caused many problems.

LTG-101: Run Selenium in Docker Compose

---

acceptance-tests/src/test/java/uk/gov/di/test/acceptance/StepDefinitions.java
acceptance-tests/src/test/resources/uk/gov/di/test/acceptance/registration_journey.feature
src/main/resources/uk/gov/di/views/successful-registration.mustache

- Ensure the new user is unique for each test by generating a UUID. These users will be removed when the server restarts.
- So we know that a user can successfully register

LTG-83 - Add acceptance test for a registration happy path

---

ci/pipeline.yaml
manifest.yml
nginx/manifest.yml
nginx/nginx.conf

- Deploy a route service in front of Selenium to limit access to Concourse workers
- Deploy and teardown Selenium, and its route service, in the Acceptance Test job.
To be able to run acceptance in the pipeline but ensure no external actors can send tests to Selenium.

LTG-101: Secure Access to Selenium from Concourse

---

ci/pipeline.yaml

- Make the `deploy-app` job serial in the same serial group as acceptance tests.
- Acceptance tests will fail if another deploy has kicked off and is restarting the app.

BAU: Make `deploy-app` a serial job co-ordinated with Selenium
